### ISSUE TITLE
Is it possible to create hierarchies of event types?

### ISSUE THREAD

**Issue by detzt** [pointcache/BasicEventBus#1]
I want to use this EventBus in my current project (a game built with Unity3D) and would like to group events. For example:

There are several items and activating them has all kinds of effects. Therefore I have an BombActivated, AcidActivated, LaserActivated, etc. So far so good.
Now some objects need to react to an item activation in general, regardless of the item type.

Is there a way to create an ItemActivated event that those objects can register for?

My first idea was to let BombActivated inherit from ItemActivated, but that doesn't work with structs.
My second idea was to have an interface which is implemented by all XxxActivated events, but then I cannot subscribe to that (it says the IEventReceiver<T> parameter T must be non-nullable).

Is there a way to achieve this?

PS: Not sure if this is the correct place to ask 😉

**Comment by pointcache** [comment]
Yeah that would be problematic with structs. 
You can create ItemActivated and fire it separately regardless of type.

**Comment by detzt** [comment]
Okay then it is not as useful as I hoped, but thanks for the response 😉
