### ISSUE TITLE
Removing binding at index 0 when count > 1 results in binding[count] being silently dropped

### ISSUE THREAD

**Issue by codetaylor** [pointcache/BasicEventBus#2]
https://github.com/pointcache/BasicEventBus/blob/master/Assets/Plugins/EventBus/EventBus.cs#L190

I believe this is intended to remove the element at index `0` when `count == 1` without a swap, however it has unintended behavior if `count > 1`. The binding at `bindings[count]` is silently dropped and a null binding is introduced at index `0` which causes issues with the loop in `Raise(...)`.

This would handle removal of the last element without the swap:

```csharp
if (index == count - 1)
{
    bindings[count - 1] = null;
    binding.InternalIndex = -1;
    count--;
    return;
}
```

**Comment by pointcache** [comment]
Thank you, solved 2 issues in one
