### ISSUE TITLE
Missing indexers

### ISSUE THREAD

**Issue by codetaylor** [pointcache/BasicEventBus#3]
https://github.com/pointcache/BasicEventBus/blob/master/Assets/Plugins/EventBus/EventBus.cs#L61

Missing `[i]`, should be:
```csharp
var type = assemblyCSharp[i];
```

https://github.com/pointcache/BasicEventBus/blob/master/Assets/Plugins/EventBus/EventBus.cs#L70

Missing `[i]`, should be:
```csharp
var type = assemblyCSharpFirstpass[i];
```

**Comment by pointcache** [comment]
Thank you
